### ISSUE TITLE
Добавить больницы

### ISSUE THREAD

**Issue by alexeypetrenko** [igorlukanin/healthcare-map#1]
Привет. На карте не хватает
	

Больницы:
 - `ООО "Медицина АльфаСтрахования" (Клиника "Альфа-центр Здоровья")	Екатеринбург, ул. Горького , д.17`
 - `ООО "Диагностика-2000"	620075  г.Екатеринбург, ул.Мамина-Сибиряка, д.171а`

Стоматология:
 - `ООО "Клиника АВЕРОН"	620146  г.Екатеринбург, ул.Фурманова, д.125, к.литер "А", кв.13, 18-24, 28, 45-54`

**Comment by igorlukanin** [comment]
А на какой именно карте? Дай ссылку, пожалуйста. Карт много.

**Comment by alexeypetrenko** [comment]
Ни на одной из этого репозитория.

**Comment by igorlukanin** [comment]
Тогда я не знаю, как я могу помочь...

**Comment by alexeypetrenko** [comment]
https://igorlukanin.github.io/healthcare-map/
Если это тебе поможет. Но вообще странно - что ты не занешь какие больницы должны быть  на какой карте.

Я выдрал все больницы по ДМС / Проверил что их нет на карте и нет ни в одном из файлов конфига этого репозитория и дал тебе конкретный список из трех. И при всём этом ты не знаешь как помочь...

**Comment by igorlukanin** [comment]
Мои знания сконцентрированы вот в этом файле: https://github.com/igorlukanin/healthcare-map/blob/gh-pages/_data/cities.yml

Там есть «города». Например, «Екатеринбург» или «Астрахань (Рисковая региональная-2017)». Они все доступны по ссылкам как отдельные карты. Например, вот [вторая](https://igorlukanin.github.io/healthcare-map/#Астрахань%20(Рисковая%20региональная-2017))

Чтобы добавить эти больницы, надо понимать, к какому городу и программе страхования их нужно добавлять, верно? Об этом я и спросил.

Отдельно вызывает вопросы, как ты проверил, что в файлах нет клиник из первого сообщения. Вот, например, самая первая клиника, о которой ты пишешь, на одной из карт: https://github.com/igorlukanin/healthcare-map/blob/gh-pages/_data/cities.yml#L1695

**Comment by alexeypetrenko** [comment]
Город указал в первом сообщении.

Про Альфа-страхование получилось конечно иронично. Так как именно с её отсутствия на карте я и начал сверять. Проверял grepом. Проскочил видимо из-за другого формата адреса.

Всё равно не понятно почему её нет на карте.

**Comment by igorlukanin** [comment]
Поставил счётчик, посмотрел на статистику. Кроме тебя и меня никто туда не заходит.

<img width="713" alt="screen shot 2017-12-04 at 00 25 32" src="https://user-images.githubusercontent.com/3852894/33528856-d3323f74-d889-11e7-990a-9bab634c1f12.png">

Спросил Вову Недельского — им эти карты тоже не нужны. Выходит, можно со спокойной душой ничего не фиксить.

Однако, спасибо за внимательность :)
